#!/bin/bash

apt-get install python-pip -y
pip install awscli

version=$(cat cf7-cli-latest/version)
aws s3 ls --region "${region_name:?missing region_name}" \
  "s3://${bucket:?missing bucket}/releases/v${version}/"

aws s3 sync --region "${region_name:?missing region_name}" \
  "s3://${bucket:?missing bucket}/releases/v${version}/"   \
  files/

exit 1