meta:
  name:    cf7-cli-releases
  # fly -t ohio-cf login -c https://ci2.starkandwayne.com -n cfcommunity
  target:  ohio-cf
  url:     https://ci2.starkandwayne.com

  github:
    owner:  cloudfoundry-community
    repo:   (( grab meta.name ))
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  aws:
    access_key: ((aws-cfcommunity-access))
    secret_key: ((aws-cfcommunity-secret))
